import { useState } from "preact/hooks";
import { Renderer } from "./components/Renderer.tsx";

export function App() {
  return (
    <>
      <Renderer
        config={{
          _id: "64c7848f32c31481781805ae",
          name: "Phone Overlay",
          type: "regular",
          settings: {
            width: 1920,
            height: 1080,
            name: "1080p",
          },
          widgets: [
            {
              id: 2,
              group: null,
              version: 1,
              type: "image",
              name: null,
              visible: true,
              locked: false,
              listener: false,
              css: {
                "z-index": 2,
                width: "1376.65px",
                height: "775.43px",
                opacity: 1,
                top: "307px",
                left: "328.91px",
              },
              text: {
                type: "text",
                value: null,
                enableShadow: true,
                scrolling: {
                  direction: "left",
                  speed: 6,
                },
                css: {
                  position: "relative",
                  "z-index": 1,
                  "font-family": "Nunito",
                  "font-size": 24,
                  color: "#fff",
                  "font-weight": "bold",
                  "text-shadow": "rgb(0, 0, 0) 1px 1px 1px",
                  "text-align": "left",
                  "line-height": 1.3,
                  scrolling: {
                    direction: "left",
                  },
                  message: {
                    enableShadow: false,
                    "font-family": "Nunito",
                    "font-size": 16,
                    "line-height": 1.3,
                    color: "#fff",
                    "text-align": "center",
                  },
                },
              },
              image: {
                type: "image",
                css: {
                  "max-width": "100%",
                  width: "100%",
                },
                src: "https://cdn.streamelements.com/uploads/148511db-8a54-446f-ac04-ff09924e8069.png",
                volume: 0.5,
              },
              video: {
                type: "video",
                volume: 0.5,
                css: {
                  width: 320,
                  height: 240,
                },
              },
              audio: {
                volume: 1,
              },
              provider: "twitch",
            },
            {
              id: 3,
              group: null,
              version: 2.2,
              type: "se-widget-alert-box",
              name: null,
              visible: true,
              locked: false,
              listeners: {
                "tip-latest": false,
                "subscriber-latest": true,
                "follower-latest": false,
                "cheer-latest": true,
                "host-latest": false,
                "raid-latest": true,
                "purchase-latest": true,
                "charityCampaignDonation-latest": false,
              },
              css: {
                "z-index": 3,
                width: "595.86px",
                height: "388.79px",
                opacity: 1,
                top: "70px",
                left: "662px",
              },
              text: {
                type: "text",
                value: null,
                enableShadow: true,
                scrolling: {
                  direction: "left",
                  speed: 6,
                },
                css: {
                  position: "relative",
                  "z-index": 1,
                  "font-family": "Nunito",
                  "font-size": 24,
                  color: "#fff",
                  "font-weight": "bold",
                  "text-shadow": "rgb(0, 0, 0) 1px 1px 1px",
                  "text-align": "left",
                  "line-height": 1.3,
                  scrolling: {
                    direction: "left",
                  },
                  message: {
                    enableShadow: false,
                    "font-family": "Nunito",
                    "font-size": 16,
                    "line-height": 1.3,
                    color: "#fff",
                    "text-align": "center",
                  },
                },
              },
              image: {
                type: "image",
                css: {
                  "max-width": "100%",
                },
              },
              video: {
                type: "video",
                volume: 0.5,
                css: {
                  width: 320,
                  height: 240,
                },
              },
              audio: {
                volume: 1,
              },
              variables: {
                animation: {
                  in: "fadeIn",
                  inDuration: 1,
                  out: "fadeOut",
                  outDuration: 1,
                },
                follower: {
                  animation: {
                    in: "none",
                    inDuration: 0,
                    out: "none",
                    outDuration: 0,
                  },
                  enableRandomPick: true,
                  enabled: true,
                  duration: 10,
                  layout: "column",
                  tts: {
                    enabled: false,
                    voice: "Brian",
                    volume: 0.75,
                    minAmount: 0,
                  },
                  text: {
                    animation: "pulse",
                    css: {
                      "font-family": "Nunito",
                      "font-size": 30,
                      color: "#ffffff",
                      "font-weight": "bold",
                      "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                      "text-align": "center",
                      "margin-top": -50,
                      highlights: {
                        color: "rgb(106, 111, 252)",
                      },
                      message: {
                        "font-size": 16,
                        "font-family": "Nunito",
                        color: "#ffffff",
                        "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                        "text-align": "center",
                        margin: "0 auto",
                      },
                    },
                    enableShadow: true,
                    message: "{name} is now following!",
                  },
                  graphics: {
                    src: "https://cdn.streamelements.com/static/alertbox/ALERT_HEART_converted.webm",
                    type: "video",
                    volume: 0.5,
                  },
                  audio: {
                    src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                    volume: 0.5,
                  },
                  variations: [],
                },
                subscriber: {
                  animation: {
                    in: "none",
                    inDuration: 0,
                    out: "none",
                    outDuration: 0,
                    text: {
                      in: "none",
                      out: "none",
                      delay: 0,
                      offset: 0,
                      inDuration: 1,
                      outDuration: 1,
                    },
                  },
                  enableRandomPick: true,
                  enabled: true,
                  duration: 5,
                  layout: "column",
                  tts: {
                    enabled: true,
                    voice: "Brian",
                    volume: 0.75,
                    minAmount: 0,
                  },
                  text: {
                    animation: "pulse",
                    css: {
                      "font-family": "Nunito",
                      "font-size": 30,
                      color: "#ffffff",
                      "font-weight": "bold",
                      "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                      "text-align": "center",
                      "margin-top": -50,
                      highlights: {
                        color: "rgb(106, 111, 252)",
                      },
                      message: {
                        "font-size": 16,
                        "font-family": "Nunito",
                        color: "#ffffff",
                        "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                        "text-align": "center",
                        margin: "0 auto",
                        "padding-top": 0,
                        "padding-right": 0,
                        "padding-bottom": 0,
                        "padding-left": 0,
                      },
                    },
                    enableShadow: true,
                    message: "{name} just subscribed!",
                  },
                  graphics: {
                    src: "https://cdn.streamelements.com/uploads/224f575b-051d-4933-b2f1-0a039a3cf88b.gif",
                    type: "image",
                    volume: 0.5,
                  },
                  audio: {
                    src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                    volume: 0.5,
                  },
                  variations: [
                    {
                      name: "Resubscriber",
                      type: "amount",
                      condition: "ATLEAST",
                      requirement: 2,
                      enabled: true,
                      chance: 100,
                      settings: {
                        animation: {
                          in: "none",
                          inDuration: 0,
                          out: "none",
                          outDuration: 0,
                          text: {
                            in: "none",
                            out: "none",
                            delay: 0,
                            offset: 0,
                            inDuration: 1,
                            outDuration: 1,
                          },
                        },
                        enableRandomPick: true,
                        enabled: true,
                        duration: 10,
                        layout: "column",
                        tts: {
                          enabled: true,
                          voice: "Brian",
                          volume: 0.75,
                          minAmount: 0,
                        },
                        text: {
                          animation: "pulse",
                          css: {
                            "font-family": "Nunito",
                            "font-size": 30,
                            color: "#ffffff",
                            "font-weight": "bold",
                            "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                            "text-align": "center",
                            "margin-top": -50,
                            highlights: {
                              color: "rgb(106, 111, 252)",
                            },
                            message: {
                              "font-size": 16,
                              "font-family": "Nunito",
                              color: "#ffffff",
                              "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                              "text-align": "center",
                              margin: "0 auto",
                              "padding-top": 0,
                              "padding-right": 0,
                              "padding-bottom": 0,
                              "padding-left": 0,
                            },
                          },
                          enableShadow: true,
                          message:
                            "{name} just resubscribed for {amount} months",
                        },
                        graphics: {
                          src: "https://cdn.streamelements.com/uploads/224f575b-051d-4933-b2f1-0a039a3cf88b.gif",
                          type: "image",
                          volume: 0.5,
                        },
                        audio: {
                          src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                          volume: 0.5,
                        },
                        variations: [],
                        showMessage: true,
                      },
                    },
                    {
                      name: "Subscriber gift",
                      type: "gift",
                      condition: "EXACT",
                      enabled: true,
                      chance: 100,
                      settings: {
                        animation: {
                          in: "none",
                          inDuration: 0,
                          out: "none",
                          outDuration: 0,
                          text: {
                            in: "none",
                            out: "none",
                            delay: 0,
                            offset: 0,
                            inDuration: 1,
                            outDuration: 1,
                          },
                        },
                        enableRandomPick: true,
                        enabled: true,
                        duration: 10,
                        layout: "column",
                        tts: {
                          enabled: true,
                          voice: "Brian",
                          volume: 0.75,
                          minAmount: 0,
                        },
                        text: {
                          message: "{sender} gifted\n {name} a subscription!",
                          css: {
                            message: {
                              "padding-top": 0,
                              "padding-right": 0,
                              "padding-bottom": 0,
                              "padding-left": 0,
                            },
                            highlights: {
                              color: "#4aaa70",
                            },
                          },
                          animation: "bounce",
                        },
                        graphics: {
                          src: "https://cdn.streamelements.com/uploads/224f575b-051d-4933-b2f1-0a039a3cf88b.gif",
                          volume: 0.5,
                          type: "image",
                        },
                        audio: {
                          src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                          volume: 0.5,
                        },
                        variations: [],
                        showMessage: true,
                      },
                    },
                    {
                      name: "Community gifts",
                      type: "communityGift",
                      condition: "ATLEAST",
                      enabled: true,
                      chance: 100,
                      requirement: 0,
                      settings: {
                        animation: {
                          in: "none",
                          inDuration: 0,
                          out: "none",
                          outDuration: 0,
                          text: {
                            in: "none",
                            out: "none",
                            delay: 0,
                            offset: 0,
                            inDuration: 1,
                            outDuration: 1,
                          },
                        },
                        enableRandomPick: true,
                        enabled: true,
                        duration: 10,
                        layout: "column",
                        tts: {
                          enabled: true,
                          voice: "Brian",
                          volume: 0.75,
                          minAmount: 0,
                        },
                        text: {
                          message: "{sender} just gifted\n {amount} subs!",
                          css: {
                            message: {
                              "padding-top": 0,
                              "padding-right": 0,
                              "padding-bottom": 0,
                              "padding-left": 0,
                            },
                            highlights: {
                              color: "#4aaa70",
                            },
                          },
                          animation: "bounce",
                        },
                        graphics: {
                          src: "https://cdn.streamelements.com/uploads/224f575b-051d-4933-b2f1-0a039a3cf88b.gif",
                          volume: 0.5,
                          type: "image",
                        },
                        audio: {
                          src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                          volume: 0.5,
                        },
                        variations: [],
                        showMessage: true,
                      },
                    },
                  ],
                  showMessage: true,
                },
                tip: {
                  animation: {
                    in: "none",
                    inDuration: 0,
                    out: "none",
                    outDuration: 0,
                    text: {
                      in: "none",
                      out: "none",
                      delay: 0,
                      offset: 0,
                      inDuration: 1,
                      outDuration: 1,
                    },
                  },
                  enableRandomPick: true,
                  enabled: true,
                  duration: 5,
                  layout: "column",
                  tts: {
                    enabled: false,
                    voice: "Brian",
                    volume: 0.75,
                    minAmount: 0,
                  },
                  text: {
                    animation: "pulse",
                    css: {
                      "font-family": "Nunito",
                      "font-size": 30,
                      color: "#ffffff",
                      "font-weight": "bold",
                      "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                      "text-align": "center",
                      "margin-top": -50,
                      highlights: {
                        color: "rgb(106, 111, 252)",
                      },
                      message: {
                        "font-size": 16,
                        "font-family": "Nunito",
                        color: "#ffffff",
                        "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                        "text-align": "center",
                        margin: "0 auto",
                        "padding-top": 0,
                        "padding-right": 0,
                        "padding-bottom": 0,
                        "padding-left": 0,
                      },
                    },
                    enableShadow: true,
                    message: "{name} tipped {currency}{amount}!",
                  },
                  graphics: {
                    src: "https://cdn.streamelements.com/static/alertbox/ALERT_COINS_converted.webm",
                    type: "video",
                    volume: 0.5,
                  },
                  audio: {
                    src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                    volume: 0.5,
                  },
                  variations: [],
                },
                charityCampaignDonation: {
                  animation: {
                    in: "none",
                    inDuration: 0,
                    out: "none",
                    outDuration: 0,
                  },
                  enableRandomPick: true,
                  enabled: true,
                  duration: 10,
                  layout: "column",
                  tts: {
                    enabled: false,
                    voice: "Brian",
                    volume: 0.75,
                    minAmount: 0,
                  },
                  text: {
                    animation: "pulse",
                    css: {
                      "font-family": "Nunito",
                      "font-size": 30,
                      color: "#ffffff",
                      "font-weight": "bold",
                      "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                      "text-align": "center",
                      "margin-top": -50,
                      highlights: {
                        color: "rgb(106, 111, 252)",
                      },
                      message: {
                        "font-size": 16,
                        "font-family": "Nunito",
                        color: "#ffffff",
                        "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                        "text-align": "center",
                        margin: "0 auto",
                      },
                    },
                    enableShadow: true,
                    message: "{name} donated {currency}{amount} to charity!",
                  },
                  graphics: {
                    src: "https://cdn.streamelements.com/static/alertbox/ALERT_COINS_converted.webm",
                    type: "video",
                    volume: 0.5,
                  },
                  audio: {
                    src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                    volume: 0.5,
                  },
                  variations: [],
                },
                host: {
                  animation: {
                    in: "none",
                    inDuration: 0,
                    out: "none",
                    outDuration: 0,
                  },
                  enableRandomPick: true,
                  enabled: true,
                  duration: 10,
                  layout: "column",
                  tts: {
                    enabled: false,
                    voice: "Brian",
                    volume: 0.75,
                    minAmount: 0,
                  },
                  text: {
                    animation: "pulse",
                    css: {
                      "font-family": "Nunito",
                      "font-size": 30,
                      color: "#ffffff",
                      "font-weight": "bold",
                      "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                      "text-align": "center",
                      "margin-top": -50,
                      highlights: {
                        color: "rgb(106, 111, 252)",
                      },
                      message: {
                        "font-size": 16,
                        "font-family": "Nunito",
                        color: "#ffffff",
                        "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                        "text-align": "center",
                        margin: "0 auto",
                      },
                    },
                    enableShadow: true,
                    message:
                      "{name} is now hosting my stream with {amount} viewers!",
                  },
                  graphics: {
                    src: "https://cdn.streamelements.com/static/alertbox/ALERT_USER_converted.webm",
                    type: "video",
                    volume: 0.5,
                  },
                  audio: {
                    src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                    volume: 0.5,
                  },
                  variations: [],
                  minAmount: 1,
                },
                raid: {
                  animation: {
                    in: "none",
                    inDuration: 0,
                    out: "none",
                    outDuration: 0,
                    text: {
                      in: "none",
                      out: "none",
                      delay: 0,
                      offset: 0,
                      inDuration: 1,
                      outDuration: 1,
                    },
                  },
                  enableRandomPick: true,
                  enabled: true,
                  duration: 10,
                  layout: "column",
                  tts: {
                    enabled: false,
                    voice: "Brian",
                    volume: 0.75,
                    minAmount: 0,
                  },
                  text: {
                    animation: "pulse",
                    css: {
                      "font-family": "Nunito",
                      "font-size": 30,
                      color: "#ffffff",
                      "font-weight": "bold",
                      "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                      "text-align": "center",
                      "margin-top": -50,
                      highlights: {
                        color: "rgb(106, 111, 252)",
                      },
                      message: {
                        "font-size": 16,
                        "font-family": "Nunito",
                        color: "#ffffff",
                        "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                        "text-align": "center",
                        margin: "0 auto",
                        "padding-top": 0,
                        "padding-right": 0,
                        "padding-bottom": 0,
                        "padding-left": 0,
                      },
                    },
                    enableShadow: true,
                    message: "{name} raided my stream with {amount} viewers!",
                  },
                  graphics: {
                    src: "https://cdn.streamelements.com/static/alertbox/ALERT_RAID_converted.webm",
                    type: "video",
                    volume: 0.5,
                  },
                  audio: {
                    src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                    volume: 0.5,
                  },
                  variations: [],
                },
                cheer: {
                  animation: {
                    in: "none",
                    inDuration: 0,
                    out: "none",
                    outDuration: 0,
                    text: {
                      in: "none",
                      out: "none",
                      delay: 0,
                      offset: 0,
                      inDuration: 1,
                      outDuration: 1,
                    },
                  },
                  enableRandomPick: true,
                  enabled: true,
                  duration: 5,
                  layout: "column",
                  tts: {
                    enabled: false,
                    voice: "Brian",
                    volume: 0.75,
                    minAmount: 0,
                  },
                  text: {
                    animation: "pulse",
                    css: {
                      "font-family": "Nunito",
                      "font-size": 30,
                      color: "#ffffff",
                      "font-weight": "bold",
                      "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                      "text-align": "center",
                      "margin-top": -50,
                      highlights: {
                        color: "rgb(106, 111, 252)",
                      },
                      message: {
                        "font-size": 16,
                        "font-family": "Nunito",
                        color: "#ffffff",
                        "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                        "text-align": "center",
                        margin: "0 auto",
                        "padding-top": 0,
                        "padding-right": 0,
                        "padding-bottom": 0,
                        "padding-left": 0,
                      },
                    },
                    enableShadow: true,
                    message: "{name} cheered x{amount}",
                  },
                  graphics: {
                    src: "https://cdn.streamelements.com/static/alertbox/ALERT_DIAMOND_converted.webm",
                    type: "video",
                    volume: 0.5,
                  },
                  audio: {
                    src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                    volume: 0.5,
                  },
                  variations: [
                    {
                      name: "Bits 1",
                      condition: "ATLEAST",
                      requirement: 1,
                      layout: "column",
                      settings: {
                        graphics: {
                          src: "https://cdn.streamelements.com/static/alertbox/BIT_1_converted.webm",
                          type: "video",
                          volume: 0.5,
                        },
                        audio: {
                          src: "https://cdn.streamelements.com/bits/audio/SciFi_1.wav",
                        },
                        text: {
                          message: "{name} cheered x{amount}",
                          animation: "none",
                          css: {
                            "font-family": "Nunito",
                            "font-size": 30,
                            color: "#ffffff",
                            "font-weight": "bold",
                            "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                            "text-align": "center",
                            "margin-top": -50,
                            highlights: {
                              color: "rgb(106, 111, 252)",
                            },
                            message: {
                              "font-size": 16,
                              "font-family": "Nunito",
                              color: "#ffffff",
                              "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                              "text-align": "center",
                              margin: "0 auto",
                            },
                          },
                          enableShadow: true,
                        },
                      },
                      enabled: true,
                    },
                    {
                      name: "Bits 100",
                      condition: "ATLEAST",
                      requirement: 100,
                      settings: {
                        graphics: {
                          src: "https://cdn.streamelements.com/static/alertbox/BIT_2_converted.webm",
                          type: "video",
                          volume: 0.5,
                        },
                        audio: {
                          src: "https://cdn.streamelements.com/bits/audio/SciFi_100.wav",
                        },
                        text: {
                          message: "{name} cheered x{amount}",
                          animation: "none",
                          css: {
                            "font-family": "Nunito",
                            "font-size": 30,
                            color: "#ffffff",
                            "font-weight": "bold",
                            "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                            "text-align": "center",
                            "margin-top": -50,
                            highlights: {
                              color: "rgb(106, 111, 252)",
                            },
                            message: {
                              "font-size": 16,
                              "font-family": "Nunito",
                              color: "#ffffff",
                              "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                              "text-align": "center",
                              margin: "0 auto",
                            },
                          },
                          enableShadow: true,
                        },
                      },
                      enabled: true,
                    },
                    {
                      name: "Bits 1000",
                      condition: "ATLEAST",
                      requirement: 1000,
                      settings: {
                        graphics: {
                          src: "https://cdn.streamelements.com/static/alertbox/BIT_3_converted.webm",
                          type: "video",
                          volume: 0.5,
                        },
                        audio: {
                          src: "https://cdn.streamelements.com/bits/audio/SciFi_1000.wav",
                        },
                        text: {
                          message: "{name} cheered x{amount}",
                          animation: "none",
                          css: {
                            "font-family": "Nunito",
                            "font-size": 30,
                            color: "#ffffff",
                            "font-weight": "bold",
                            "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                            "text-align": "center",
                            "margin-top": -50,
                            highlights: {
                              color: "rgb(106, 111, 252)",
                            },
                            message: {
                              "font-size": 16,
                              "font-family": "Nunito",
                              color: "#ffffff",
                              "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                              "text-align": "center",
                              margin: "0 auto",
                            },
                          },
                          enableShadow: true,
                        },
                      },
                      enabled: true,
                    },
                    {
                      name: "Bits 5000",
                      condition: "ATLEAST",
                      requirement: 5000,
                      settings: {
                        graphics: {
                          src: "https://cdn.streamelements.com/static/alertbox/BIT_4_converted.webm",
                          type: "video",
                          volume: 0.5,
                        },
                        audio: {
                          src: "https://cdn.streamelements.com/bits/audio/SciFi_5000.wav",
                        },
                        text: {
                          message: "{name} cheered x{amount}",
                          animation: "none",
                          css: {
                            "font-family": "Nunito",
                            "font-size": 30,
                            color: "#ffffff",
                            "font-weight": "bold",
                            "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                            "text-align": "center",
                            "margin-top": -50,
                            highlights: {
                              color: "rgb(106, 111, 252)",
                            },
                            message: {
                              "font-size": 16,
                              "font-family": "Nunito",
                              color: "#ffffff",
                              "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                              "text-align": "center",
                              margin: "0 auto",
                            },
                          },
                          enableShadow: true,
                        },
                      },
                      enabled: true,
                    },
                    {
                      name: "Bits 10000",
                      condition: "ATLEAST",
                      requirement: 10000,
                      settings: {
                        graphics: {
                          src: "https://cdn.streamelements.com/static/alertbox/BIT_5_converted.webm",
                          type: "video",
                          volume: 0.5,
                        },
                        audio: {
                          src: "https://cdn.streamelements.com/bits/audio/SciFi_10000.wav",
                        },
                        text: {
                          message: "{name} cheered x{amount}",
                          animation: "none",
                          css: {
                            "font-family": "Nunito",
                            "font-size": 30,
                            color: "#ffffff",
                            "font-weight": "bold",
                            "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                            "text-align": "center",
                            "margin-top": -50,
                            highlights: {
                              color: "rgb(106, 111, 252)",
                            },
                            message: {
                              "font-size": 16,
                              "font-family": "Nunito",
                              color: "#ffffff",
                              "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                              "text-align": "center",
                              margin: "0 auto",
                            },
                          },
                          enableShadow: true,
                        },
                      },
                      enabled: true,
                    },
                  ],
                },
                merch: {
                  animation: {
                    in: "none",
                    inDuration: 0,
                    out: "none",
                    outDuration: 0,
                  },
                  enableRandomPick: true,
                  enabled: true,
                  duration: 10,
                  layout: "column",
                  tts: {
                    enabled: false,
                    voice: "Brian",
                    volume: 0.75,
                    minAmount: 0,
                  },
                  text: {
                    animation: "pulse",
                    css: {
                      "font-family": "Nunito",
                      "font-size": 30,
                      color: "#ffffff",
                      "font-weight": "bold",
                      "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                      "text-align": "center",
                      "margin-top": -50,
                      highlights: {
                        color: "rgb(106, 111, 252)",
                      },
                      message: {
                        "font-size": 16,
                        "font-family": "Nunito",
                        color: "#ffffff",
                        "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                        "text-align": "center",
                        margin: "0 auto",
                      },
                    },
                    enableShadow: true,
                    message: "{name} just bought {items}!",
                  },
                  graphics: {
                    src: "https://cdn.streamelements.com/merch/self-serve/AdvancedMerchAlerts.webm",
                    type: "video",
                    volume: 0.5,
                  },
                  audio: {
                    src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                    volume: 0.5,
                  },
                  variations: [],
                },
                purchase: {
                  animation: {
                    in: "none",
                    inDuration: 0,
                    out: "none",
                    outDuration: 0,
                  },
                  enableRandomPick: true,
                  enabled: true,
                  duration: 10,
                  layout: "column",
                  tts: {
                    enabled: false,
                    voice: "Brian",
                    volume: 0.75,
                    minAmount: 0,
                  },
                  text: {
                    animation: "pulse",
                    css: {
                      "font-family": "Nunito",
                      "font-size": 30,
                      color: "#ffffff",
                      "font-weight": "bold",
                      "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                      "text-align": "center",
                      "margin-top": -50,
                      highlights: {
                        color: "rgb(106, 111, 252)",
                      },
                      message: {
                        "font-size": 16,
                        "font-family": "Nunito",
                        color: "#ffffff",
                        "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                        "text-align": "center",
                        margin: "0 auto",
                      },
                    },
                    enableShadow: true,
                    message: "{name} purchased {items}!",
                  },
                  graphics: {
                    src: "https://cdn.streamelements.com/merch/self-serve/AdvancedMerchAlerts.webm",
                    type: "video",
                    volume: 0.5,
                  },
                  audio: {
                    src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                    volume: 0.5,
                  },
                  variations: [],
                },
              },
              provider: "twitch",
            },
            {
              id: 4,
              group: null,
              version: 1,
              type: "subscriber-latest",
              name: null,
              visible: true,
              locked: false,
              listener: "subscriber-latest",
              css: {
                "z-index": 4,
                width: "392.79px",
                height: "48.18px",
                opacity: 1,
                top: "1031.91px",
                left: "1038.17px",
              },
              text: {
                type: "text",
                value: "{name}",
                enableShadow: true,
                scrolling: {
                  direction: "left",
                  speed: 6,
                },
                css: {
                  position: "relative",
                  "z-index": 1,
                  "font-family": "Blinker",
                  "font-size": 34,
                  color: "#fff",
                  "font-weight": "normal",
                  "text-shadow": "rgb(0, 0, 0) 1px 1px 1px",
                  "text-align": "center",
                  "line-height": 1.3,
                  scrolling: {
                    direction: "left",
                  },
                  message: {
                    enableShadow: false,
                    "font-family": "Nunito",
                    "font-size": 16,
                    "line-height": 1.3,
                    color: "#fff",
                    "text-align": "center",
                    "padding-top": 0,
                    "padding-right": 0,
                    "padding-bottom": 0,
                    "padding-left": 0,
                  },
                  "text-transform": "uppercase",
                },
                enableCustomFont: true,
              },
              image: {
                type: "image",
                css: {
                  "max-width": "100%",
                },
              },
              video: {
                type: "video",
                volume: 0.5,
                css: {
                  width: 320,
                  height: 240,
                },
              },
              audio: {
                volume: 1,
              },
              provider: "twitch",
            },
            {
              id: 5,
              group: null,
              version: 2.2,
              type: "se-widget-alert-box",
              name: null,
              visible: true,
              locked: false,
              listeners: {
                "tip-latest": false,
                "subscriber-latest": false,
                "follower-latest": true,
                "cheer-latest": false,
                "host-latest": false,
                "raid-latest": false,
                "purchase-latest": false,
                "charityCampaignDonation-latest": false,
              },
              css: {
                "z-index": 5,
                width: "459.41px",
                height: "305.05px",
                opacity: 1,
                top: "878.35px",
                left: "1460.59px",
              },
              text: {
                type: "text",
                value: null,
                enableShadow: true,
                scrolling: {
                  direction: "left",
                  speed: 6,
                },
                css: {
                  position: "relative",
                  "z-index": 1,
                  "font-family": "Nunito",
                  "font-size": 24,
                  color: "#fff",
                  "font-weight": "bold",
                  "text-shadow": "rgb(0, 0, 0) 1px 1px 1px",
                  "text-align": "left",
                  "line-height": 1.3,
                  scrolling: {
                    direction: "left",
                  },
                  message: {
                    enableShadow: false,
                    "font-family": "Nunito",
                    "font-size": 16,
                    "line-height": 1.3,
                    color: "#fff",
                    "text-align": "center",
                  },
                },
              },
              image: {
                type: "image",
                css: {
                  "max-width": "100%",
                },
              },
              video: {
                type: "video",
                volume: 0.5,
                css: {
                  width: 320,
                  height: 240,
                },
              },
              audio: {
                volume: 1,
              },
              variables: {
                animation: {
                  in: "fadeIn",
                  inDuration: 1,
                  out: "fadeOut",
                  outDuration: 1,
                },
                follower: {
                  animation: {
                    in: "none",
                    inDuration: 0,
                    out: "none",
                    outDuration: 0,
                    text: {
                      in: "none",
                      out: "none",
                      delay: 0,
                      offset: 0,
                      inDuration: 1,
                      outDuration: 1,
                    },
                  },
                  enableRandomPick: true,
                  enabled: true,
                  duration: 3,
                  layout: "column",
                  tts: {
                    enabled: false,
                    voice: "Brian",
                    volume: 0.75,
                    minAmount: 0,
                  },
                  text: {
                    animation: "pulse",
                    css: {
                      "font-family": "Nunito",
                      "font-size": 20,
                      color: "#ffffff",
                      "font-weight": "bold",
                      "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                      "text-align": "center",
                      "margin-top": -50,
                      highlights: {
                        color: "rgb(106, 111, 252)",
                      },
                      message: {
                        "font-size": 16,
                        "font-family": "Nunito",
                        color: "#ffffff",
                        "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                        "text-align": "center",
                        margin: "0 auto",
                        "padding-top": 0,
                        "padding-right": 0,
                        "padding-bottom": 0,
                        "padding-left": 0,
                      },
                    },
                    enableShadow: true,
                    message: "{name} is now following!",
                  },
                  graphics: {
                    src: "https://cdn.streamelements.com/static/alertbox/ALERT_HEART_converted.webm",
                    type: "video",
                    volume: 0.5,
                  },
                  audio: {
                    src: null,
                    volume: 0.1,
                  },
                  variations: [],
                },
                subscriber: {
                  animation: {
                    in: "none",
                    inDuration: 0,
                    out: "none",
                    outDuration: 0,
                  },
                  enableRandomPick: true,
                  enabled: true,
                  duration: 10,
                  layout: "column",
                  tts: {
                    enabled: false,
                    voice: "Brian",
                    volume: 0.75,
                    minAmount: 0,
                  },
                  text: {
                    animation: "pulse",
                    css: {
                      "font-family": "Nunito",
                      "font-size": 30,
                      color: "#ffffff",
                      "font-weight": "bold",
                      "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                      "text-align": "center",
                      "margin-top": -50,
                      highlights: {
                        color: "rgb(106, 111, 252)",
                      },
                      message: {
                        "font-size": 16,
                        "font-family": "Nunito",
                        color: "#ffffff",
                        "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                        "text-align": "center",
                        margin: "0 auto",
                      },
                    },
                    enableShadow: true,
                    message: "{name} just subscribed!",
                  },
                  graphics: {
                    src: "https://cdn.streamelements.com/static/alertbox/ALERT_STAR_converted.webm",
                    type: "video",
                    volume: 0.5,
                  },
                  audio: {
                    src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                    volume: 0.5,
                  },
                  variations: [
                    {
                      name: "Resubscriber",
                      type: "amount",
                      condition: "ATLEAST",
                      requirement: 2,
                      enabled: true,
                      chance: 100,
                      settings: {
                        animation: {
                          in: "none",
                          inDuration: 0,
                          out: "none",
                          outDuration: 0,
                        },
                        enableRandomPick: true,
                        enabled: true,
                        duration: 10,
                        layout: "column",
                        tts: {
                          enabled: false,
                          voice: "Brian",
                          volume: 0.75,
                          minAmount: 0,
                        },
                        text: {
                          animation: "pulse",
                          css: {
                            "font-family": "Nunito",
                            "font-size": 30,
                            color: "#ffffff",
                            "font-weight": "bold",
                            "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                            "text-align": "center",
                            "margin-top": -50,
                            highlights: {
                              color: "rgb(106, 111, 252)",
                            },
                            message: {
                              "font-size": 16,
                              "font-family": "Nunito",
                              color: "#ffffff",
                              "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                              "text-align": "center",
                              margin: "0 auto",
                            },
                          },
                          enableShadow: true,
                          message:
                            "{name} just resubscribed for {amount} months",
                        },
                        graphics: {
                          src: "https://cdn.streamelements.com/static/alertbox/ALERT_STARS_converted.webm",
                          type: "video",
                          volume: 0.5,
                        },
                        audio: {
                          src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                          volume: 0.5,
                        },
                        variations: [],
                      },
                    },
                    {
                      name: "Subscriber gift",
                      type: "gift",
                      condition: "EXACT",
                      enabled: true,
                      chance: 100,
                      settings: {
                        animation: {
                          in: "none",
                          inDuration: 0,
                          out: "none",
                          outDuration: 0,
                        },
                        enableRandomPick: true,
                        enabled: true,
                        duration: 10,
                        layout: "column",
                        tts: {
                          enabled: false,
                          voice: "Brian",
                          volume: 0.75,
                          minAmount: 0,
                        },
                        text: {
                          message: "{sender} gifted\n {name} a subscription!",
                        },
                        graphics: {
                          src: "https://cdn.streamelements.com/static/alertbox/ALERT_GIFTBOX.webm",
                        },
                        audio: {
                          src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                          volume: 0.5,
                        },
                        variations: [],
                      },
                    },
                    {
                      name: "Community gifts",
                      type: "communityGift",
                      condition: "ATLEAST",
                      enabled: true,
                      chance: 100,
                      requirement: 0,
                      settings: {
                        animation: {
                          in: "none",
                          inDuration: 0,
                          out: "none",
                          outDuration: 0,
                        },
                        enableRandomPick: true,
                        enabled: true,
                        duration: 10,
                        layout: "column",
                        tts: {
                          enabled: false,
                          voice: "Brian",
                          volume: 0.75,
                          minAmount: 0,
                        },
                        text: {
                          message: "{sender} just gifted\n {amount} subs!",
                        },
                        graphics: {
                          src: "https://cdn.streamelements.com/static/alertbox/ALERT_GIFTBOX.webm",
                        },
                        audio: {
                          src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                          volume: 0.5,
                        },
                        variations: [],
                      },
                    },
                  ],
                },
                tip: {
                  animation: {
                    in: "none",
                    inDuration: 0,
                    out: "none",
                    outDuration: 0,
                  },
                  enableRandomPick: true,
                  enabled: true,
                  duration: 10,
                  layout: "column",
                  tts: {
                    enabled: false,
                    voice: "Brian",
                    volume: 0.75,
                    minAmount: 0,
                  },
                  text: {
                    animation: "pulse",
                    css: {
                      "font-family": "Nunito",
                      "font-size": 30,
                      color: "#ffffff",
                      "font-weight": "bold",
                      "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                      "text-align": "center",
                      "margin-top": -50,
                      highlights: {
                        color: "rgb(106, 111, 252)",
                      },
                      message: {
                        "font-size": 16,
                        "font-family": "Nunito",
                        color: "#ffffff",
                        "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                        "text-align": "center",
                        margin: "0 auto",
                      },
                    },
                    enableShadow: true,
                    message: "{name} tipped {currency}{amount}!",
                  },
                  graphics: {
                    src: "https://cdn.streamelements.com/static/alertbox/ALERT_COINS_converted.webm",
                    type: "video",
                    volume: 0.5,
                  },
                  audio: {
                    src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                    volume: 0.5,
                  },
                  variations: [],
                },
                charityCampaignDonation: {
                  animation: {
                    in: "none",
                    inDuration: 0,
                    out: "none",
                    outDuration: 0,
                  },
                  enableRandomPick: true,
                  enabled: true,
                  duration: 10,
                  layout: "column",
                  tts: {
                    enabled: false,
                    voice: "Brian",
                    volume: 0.75,
                    minAmount: 0,
                  },
                  text: {
                    animation: "pulse",
                    css: {
                      "font-family": "Nunito",
                      "font-size": 30,
                      color: "#ffffff",
                      "font-weight": "bold",
                      "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                      "text-align": "center",
                      "margin-top": -50,
                      highlights: {
                        color: "rgb(106, 111, 252)",
                      },
                      message: {
                        "font-size": 16,
                        "font-family": "Nunito",
                        color: "#ffffff",
                        "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                        "text-align": "center",
                        margin: "0 auto",
                      },
                    },
                    enableShadow: true,
                    message: "{name} donated {currency}{amount} to charity!",
                  },
                  graphics: {
                    src: "https://cdn.streamelements.com/static/alertbox/ALERT_COINS_converted.webm",
                    type: "video",
                    volume: 0.5,
                  },
                  audio: {
                    src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                    volume: 0.5,
                  },
                  variations: [],
                },
                host: {
                  animation: {
                    in: "none",
                    inDuration: 0,
                    out: "none",
                    outDuration: 0,
                  },
                  enableRandomPick: true,
                  enabled: true,
                  duration: 10,
                  layout: "column",
                  tts: {
                    enabled: false,
                    voice: "Brian",
                    volume: 0.75,
                    minAmount: 0,
                  },
                  text: {
                    animation: "pulse",
                    css: {
                      "font-family": "Nunito",
                      "font-size": 30,
                      color: "#ffffff",
                      "font-weight": "bold",
                      "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                      "text-align": "center",
                      "margin-top": -50,
                      highlights: {
                        color: "rgb(106, 111, 252)",
                      },
                      message: {
                        "font-size": 16,
                        "font-family": "Nunito",
                        color: "#ffffff",
                        "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                        "text-align": "center",
                        margin: "0 auto",
                      },
                    },
                    enableShadow: true,
                    message:
                      "{name} is now hosting my stream with {amount} viewers!",
                  },
                  graphics: {
                    src: "https://cdn.streamelements.com/static/alertbox/ALERT_USER_converted.webm",
                    type: "video",
                    volume: 0.5,
                  },
                  audio: {
                    src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                    volume: 0.5,
                  },
                  variations: [],
                  minAmount: 1,
                },
                raid: {
                  animation: {
                    in: "none",
                    inDuration: 0,
                    out: "none",
                    outDuration: 0,
                  },
                  enableRandomPick: true,
                  enabled: true,
                  duration: 10,
                  layout: "column",
                  tts: {
                    enabled: false,
                    voice: "Brian",
                    volume: 0.75,
                    minAmount: 0,
                  },
                  text: {
                    animation: "pulse",
                    css: {
                      "font-family": "Nunito",
                      "font-size": 30,
                      color: "#ffffff",
                      "font-weight": "bold",
                      "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                      "text-align": "center",
                      "margin-top": -50,
                      highlights: {
                        color: "rgb(106, 111, 252)",
                      },
                      message: {
                        "font-size": 16,
                        "font-family": "Nunito",
                        color: "#ffffff",
                        "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                        "text-align": "center",
                        margin: "0 auto",
                      },
                    },
                    enableShadow: true,
                    message: "{name} raided my stream with {amount} viewers!",
                  },
                  graphics: {
                    src: "https://cdn.streamelements.com/static/alertbox/ALERT_RAID_converted.webm",
                    type: "video",
                    volume: 0.5,
                  },
                  audio: {
                    src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                    volume: 0.5,
                  },
                  variations: [],
                },
                cheer: {
                  animation: {
                    in: "none",
                    inDuration: 0,
                    out: "none",
                    outDuration: 0,
                  },
                  enableRandomPick: true,
                  enabled: true,
                  duration: 10,
                  layout: "column",
                  tts: {
                    enabled: false,
                    voice: "Brian",
                    volume: 0.75,
                    minAmount: 0,
                  },
                  text: {
                    animation: "pulse",
                    css: {
                      "font-family": "Nunito",
                      "font-size": 30,
                      color: "#ffffff",
                      "font-weight": "bold",
                      "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                      "text-align": "center",
                      "margin-top": -50,
                      highlights: {
                        color: "rgb(106, 111, 252)",
                      },
                      message: {
                        "font-size": 16,
                        "font-family": "Nunito",
                        color: "#ffffff",
                        "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                        "text-align": "center",
                        margin: "0 auto",
                      },
                    },
                    enableShadow: true,
                    message: "{name} cheered x{amount}",
                  },
                  graphics: {
                    src: "https://cdn.streamelements.com/static/alertbox/ALERT_DIAMOND_converted.webm",
                    type: "video",
                    volume: 0.5,
                  },
                  audio: {
                    src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                    volume: 0.5,
                  },
                  variations: [
                    {
                      name: "Bits 1",
                      condition: "ATLEAST",
                      requirement: 1,
                      layout: "column",
                      settings: {
                        graphics: {
                          src: "https://cdn.streamelements.com/static/alertbox/BIT_1_converted.webm",
                          type: "video",
                          volume: 0.5,
                        },
                        audio: {
                          src: "https://cdn.streamelements.com/bits/audio/SciFi_1.wav",
                        },
                        text: {
                          message: "{name} cheered x{amount}",
                          animation: "none",
                          css: {
                            "font-family": "Nunito",
                            "font-size": 30,
                            color: "#ffffff",
                            "font-weight": "bold",
                            "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                            "text-align": "center",
                            "margin-top": -50,
                            highlights: {
                              color: "rgb(106, 111, 252)",
                            },
                            message: {
                              "font-size": 16,
                              "font-family": "Nunito",
                              color: "#ffffff",
                              "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                              "text-align": "center",
                              margin: "0 auto",
                            },
                          },
                          enableShadow: true,
                        },
                      },
                    },
                    {
                      name: "Bits 100",
                      condition: "ATLEAST",
                      requirement: 100,
                      settings: {
                        graphics: {
                          src: "https://cdn.streamelements.com/static/alertbox/BIT_2_converted.webm",
                          type: "video",
                          volume: 0.5,
                        },
                        audio: {
                          src: "https://cdn.streamelements.com/bits/audio/SciFi_100.wav",
                        },
                        text: {
                          message: "{name} cheered x{amount}",
                          animation: "none",
                          css: {
                            "font-family": "Nunito",
                            "font-size": 30,
                            color: "#ffffff",
                            "font-weight": "bold",
                            "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                            "text-align": "center",
                            "margin-top": -50,
                            highlights: {
                              color: "rgb(106, 111, 252)",
                            },
                            message: {
                              "font-size": 16,
                              "font-family": "Nunito",
                              color: "#ffffff",
                              "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                              "text-align": "center",
                              margin: "0 auto",
                            },
                          },
                          enableShadow: true,
                        },
                      },
                    },
                    {
                      name: "Bits 1000",
                      condition: "ATLEAST",
                      requirement: 1000,
                      settings: {
                        graphics: {
                          src: "https://cdn.streamelements.com/static/alertbox/BIT_3_converted.webm",
                          type: "video",
                          volume: 0.5,
                        },
                        audio: {
                          src: "https://cdn.streamelements.com/bits/audio/SciFi_1000.wav",
                        },
                        text: {
                          message: "{name} cheered x{amount}",
                          animation: "none",
                          css: {
                            "font-family": "Nunito",
                            "font-size": 30,
                            color: "#ffffff",
                            "font-weight": "bold",
                            "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                            "text-align": "center",
                            "margin-top": -50,
                            highlights: {
                              color: "rgb(106, 111, 252)",
                            },
                            message: {
                              "font-size": 16,
                              "font-family": "Nunito",
                              color: "#ffffff",
                              "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                              "text-align": "center",
                              margin: "0 auto",
                            },
                          },
                          enableShadow: true,
                        },
                      },
                    },
                    {
                      name: "Bits 5000",
                      condition: "ATLEAST",
                      requirement: 5000,
                      settings: {
                        graphics: {
                          src: "https://cdn.streamelements.com/static/alertbox/BIT_4_converted.webm",
                          type: "video",
                          volume: 0.5,
                        },
                        audio: {
                          src: "https://cdn.streamelements.com/bits/audio/SciFi_5000.wav",
                        },
                        text: {
                          message: "{name} cheered x{amount}",
                          animation: "none",
                          css: {
                            "font-family": "Nunito",
                            "font-size": 30,
                            color: "#ffffff",
                            "font-weight": "bold",
                            "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                            "text-align": "center",
                            "margin-top": -50,
                            highlights: {
                              color: "rgb(106, 111, 252)",
                            },
                            message: {
                              "font-size": 16,
                              "font-family": "Nunito",
                              color: "#ffffff",
                              "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                              "text-align": "center",
                              margin: "0 auto",
                            },
                          },
                          enableShadow: true,
                        },
                      },
                    },
                    {
                      name: "Bits 10000",
                      condition: "ATLEAST",
                      requirement: 10000,
                      settings: {
                        graphics: {
                          src: "https://cdn.streamelements.com/static/alertbox/BIT_5_converted.webm",
                          type: "video",
                          volume: 0.5,
                        },
                        audio: {
                          src: "https://cdn.streamelements.com/bits/audio/SciFi_10000.wav",
                        },
                        text: {
                          message: "{name} cheered x{amount}",
                          animation: "none",
                          css: {
                            "font-family": "Nunito",
                            "font-size": 30,
                            color: "#ffffff",
                            "font-weight": "bold",
                            "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                            "text-align": "center",
                            "margin-top": -50,
                            highlights: {
                              color: "rgb(106, 111, 252)",
                            },
                            message: {
                              "font-size": 16,
                              "font-family": "Nunito",
                              color: "#ffffff",
                              "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                              "text-align": "center",
                              margin: "0 auto",
                            },
                          },
                          enableShadow: true,
                        },
                      },
                    },
                  ],
                },
                merch: {
                  animation: {
                    in: "none",
                    inDuration: 0,
                    out: "none",
                    outDuration: 0,
                  },
                  enableRandomPick: true,
                  enabled: true,
                  duration: 10,
                  layout: "column",
                  tts: {
                    enabled: false,
                    voice: "Brian",
                    volume: 0.75,
                    minAmount: 0,
                  },
                  text: {
                    animation: "pulse",
                    css: {
                      "font-family": "Nunito",
                      "font-size": 30,
                      color: "#ffffff",
                      "font-weight": "bold",
                      "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                      "text-align": "center",
                      "margin-top": -50,
                      highlights: {
                        color: "rgb(106, 111, 252)",
                      },
                      message: {
                        "font-size": 16,
                        "font-family": "Nunito",
                        color: "#ffffff",
                        "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                        "text-align": "center",
                        margin: "0 auto",
                      },
                    },
                    enableShadow: true,
                    message: "{name} just bought {items}!",
                  },
                  graphics: {
                    src: "https://cdn.streamelements.com/merch/self-serve/AdvancedMerchAlerts.webm",
                    type: "video",
                    volume: 0.5,
                  },
                  audio: {
                    src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                    volume: 0.5,
                  },
                  variations: [],
                },
                purchase: {
                  animation: {
                    in: "none",
                    inDuration: 0,
                    out: "none",
                    outDuration: 0,
                  },
                  enableRandomPick: true,
                  enabled: true,
                  duration: 10,
                  layout: "column",
                  tts: {
                    enabled: false,
                    voice: "Brian",
                    volume: 0.75,
                    minAmount: 0,
                  },
                  text: {
                    animation: "pulse",
                    css: {
                      "font-family": "Nunito",
                      "font-size": 30,
                      color: "#ffffff",
                      "font-weight": "bold",
                      "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                      "text-align": "center",
                      "margin-top": -50,
                      highlights: {
                        color: "rgb(106, 111, 252)",
                      },
                      message: {
                        "font-size": 16,
                        "font-family": "Nunito",
                        color: "#ffffff",
                        "text-shadow": "rgba(0, 0, 0, 0.8) 1px 1px 1px",
                        "text-align": "center",
                        margin: "0 auto",
                      },
                    },
                    enableShadow: true,
                    message: "{name} purchased {items}!",
                  },
                  graphics: {
                    src: "https://cdn.streamelements.com/merch/self-serve/AdvancedMerchAlerts.webm",
                    type: "video",
                    volume: 0.5,
                  },
                  audio: {
                    src: "https://cdn.streamelements.com/static/alertbox/default.ogg",
                    volume: 0.5,
                  },
                  variations: [],
                },
              },
              provider: "twitch",
            },
          ],
          preview:
            "https://cdn.streamelements.com/assets/dashboard/my-overlays/overlay-default-preview-1.jpg",
          mobile: false,
          campaign: false,
          favorite: false,
          channel: "5e94fd4601b654ad643c6b01",
          createdAt: "2023-07-31T09:53:19.417Z",
          updatedAt: "2023-07-31T09:53:59.267Z",
        }}
      />
    </>
  );
}
